# Generated by Django 3.0 on 2023-11-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='android',
            name='img',
            field=models.ImageField(default='asadsas', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
